training:
  criterion: "CrossEntropyLoss"
  optimizer: "SGD"

model: "leNetV5"
#model: "MobileNetV1"
#model: "MobileNetV3"
#model: "AlexNet"

meta:
  #data_save_path: "../../images/foo"
  #data_save_path: "../../images/240508"
  #data_save_path: "../../images/240507_3"
  #data_save_path: "../../images/240504_1/tagged" # the "good" training data with the augmented images
  #data_save_path: "../240505_combined/"
  #data_save_path: "../data_trainSet1/" # 3MP training images
  #data_save_path: "../data_shortSet/"
  data_save_path: "../../images/TrainingTestSet" # gathered with our first good model
