training:
  #model: "TinyVGG"
  model: "FashionMNISTModelV2"
  criterion: "CrossEntropyLoss"
  optimizer: "SGD"
  #optimizer: "Adam"
  epochs: 1
  learning_rate: 0.1
  batch_size: 64

model:
  FashionMNISTModelV2:
    hidden_neurons: 30 

meta:
  #data_save_path: "../../images/foo"
  #data_save_path: "../../images/240507_3"
  data_save_path: "../../images/240504_1/tagged" # the "good" training data
  #data_save_path: "../240505_combined/"
  #data_save_path: "../data_trainSet1/"
  #data_save_path: "../data_shortSet/"
